apiVersion: v1
kind: Service
metadata:
  # Should correspond to the ALS_SERVICE_NAME in configmap.yaml
  name: {{ template "als-oracle-pathfinder-chart.fullname" . }}
  labels:
    app: {{ template "als-oracle-pathfinder-chart.name" . }}
    chart: {{ template "als-oracle-pathfinder-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "als-oracle-pathfinder-chart.name" . }}
    release: {{ .Release.Name }}
